### ISSUE TITLE
json_decode error: Syntax error

### ISSUE THREAD

**Issue by kura1420** [walangkaji/ztef#1]
mas qo iki json_decode error ya, berikut script ku

```
class TestController extends Controller
{
    //
    public function index()
    {
        try {
            $zte = new ZteF('192.168.1.1', 'user', 'user', true);
        
            // Get status
            $status = $zte->status()->deviceInformation();
            var_dump($status);
        
            // Reboot device
            // $reboot = $zte->administration()->systemManagement()->reboot();
            // var_dump($reboot);
        
        } catch (LoginException $e) {
            echo $e->getMessage() . \PHP_EOL;
        } catch (\Exception $e) {
            echo $e->getMessage() . \PHP_EOL;
        }
    }
}
```

env pake laravel 7.4, php 8.2

**Comment by kura1420** [comment]
bentrok sama guzzle mas

**Comment by walangkaji** [comment]
laravel 7.4 ada mas emang?

**Comment by walangkaji** [comment]
![](https://user-images.githubusercontent.com/12222084/231753264-f8fe7450-2153-46d3-8db5-ff9bbbb32b91.png)

PHP 8.0.28 | laravel 7.30.6 aman mas

coba di ```composer update```

**Comment by kura1420** [comment]
![Screen Shot 2023-04-14 at 04 32 52](https://user-images.githubusercontent.com/7526778/231887968-8fb43f57-9e8c-47dd-a51b-f1692a351750.png)

Berikut mas capturenya,, sama ini composer.json saya
```
"require": {
        "php": "^7.3|^8.0",
        "evilfreelancer/routeros-api-php": "^1.5",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.5",
        "irazasyed/telegram-bot-sdk": "^3.9",
        "jeroennoten/laravel-adminlte": "^3.8",
        "laravel/framework": "^8.75",
        "laravel/sanctum": "^2.11",
        "laravel/tinker": "^2.5",
        "laravel/ui": "^3.4",
        "spatie/laravel-permission": "^5.10",
        "walangkaji/zte-f609-api": "^1.1",
        "walangkaji/ztef": "^1.1"
    },
    "require-dev": {
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^5.10",
        "phpunit/phpunit": "^9.5.10"
    },
```

saya coba install laravel kosongan jalan mas,, 

kaya script mas bentrok disini

![Screen Shot 2023-04-14 at 04 37 22](https://user-images.githubusercontent.com/7526778/231888575-6e823ac9-4953-42a9-9d7f-0337abe4c933.png)

_vendor/walangkaji/ztef/src/ZteF.php_

**Comment by kura1420** [comment]
![Screen Shot 2023-04-14 at 05 52 04](https://user-images.githubusercontent.com/7526778/231899926-8e47a70b-1faf-49d4-8c06-54598fb93670.png)

ini mas dependenci nya

**Comment by walangkaji** [comment]
> ```
> "require": {
>         "php": "^7.3|^8.0",
>         "evilfreelancer/routeros-api-php": "^1.5",
>         "fruitcake/laravel-cors": "^2.0",
>         "guzzlehttp/guzzle": "^7.5",
>         "irazasyed/telegram-bot-sdk": "^3.9",
>         "jeroennoten/laravel-adminlte": "^3.8",
>         "laravel/framework": "^8.75",
>         "laravel/sanctum": "^2.11",
>         "laravel/tinker": "^2.5",
>         "laravel/ui": "^3.4",
>         "spatie/laravel-permission": "^5.10",
>         "walangkaji/zte-f609-api": "^1.1",
>         "walangkaji/ztef": "^1.1"
>     },
>     "require-dev": {
>         "facade/ignition": "^2.5",
>         "fakerphp/faker": "^1.9.1",
>         "laravel/sail": "^1.0.1",
>         "mockery/mockery": "^1.4.4",
>         "nunomaduro/collision": "^5.10",
>         "phpunit/phpunit": "^9.5.10"
>     },
> ```
> 
> saya coba install laravel kosongan jalan mas,,
> 
> kaya script mas bentrok disini
> 
> _vendor/walangkaji/ztef/src/ZteF.php_

saya coba dengan  dependency seperti mas diatas masih bisa berjalan normal mas,
dan itu bentroknya karena package guzzle yang ada di telegram-bot ga sesuai dengan [ManCurl](https://github.com/walangkaji/ManCurl/blob/master/composer.json) dan sudah saya sesuaikan, seharusnya sudah aman.

coba sampean update mas, 
```composer update```
```composer dump-autoload```
apakah masih sama?

**Comment by kura1420** [comment]
Blum coba lagi mas, iki ta jalan ke via command line aman. Tpi karo browser msh error kaya yg saya sampein

**Comment by walangkaji** [comment]
saya coba via browserku aman juga ki mas,
atau gini aja, sampean bikin repo dan sampean push laravel projectnya, jadi bisa tak cek errornya seperti apa dan darimana

**Comment by kura1420** [comment]
Boleh nanti ya mas,, msh ad kerjaan yg lain 🤭

Btw untuk akses ZTE OLT C300 punya reference nya ga mas biar bisa dibuat web base juga

**Comment by walangkaji** [comment]
> Boleh nanti ya mas,, msh ad kerjaan yg lain 🤭
> 
> Btw untuk akses ZTE OLT C300 punya reference nya ga mas biar bisa dibuat web base juga

aduh ga punya devicenya mas untuk debug 😄

**Comment by kura1420** [comment]
Hahaha siapp,, makasi ya mas

**Comment by walangkaji** [comment]
gimana mas? masih ada kendala kah?

**Comment by kura1420** [comment]
belum cek lagi mas, nanti ta kabari
